# Generated by Django 3.0.7 on 2020-06-25 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Disciplina', models.TextField(max_length=25, verbose_name='Disciplina')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horaria')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'db_table': 'disciplina',
                'ordering': ['Nome_Disciplina'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100, verbose_name='Nome do professor')),
                ('Exeperiencia_profissional', models.CharField(max_length=200, verbose_name='experiencia')),
                ('Hora_aula', models.TimeField(verbose_name='Tempo')),
                ('Disponibilidade', models.IntegerField(blank=True, choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno')], default=1, verbose_name='Selecione o turno')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'db_table': 'professor',
                'ordering': ['Nome'],
            },
        ),
        migrations.CreateModel(
            name='Professor_Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=20, verbose_name='Nome do curso')),
                ('semestre', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Semestre')),
                ('codigo_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_professor', to='core.Disciplina', verbose_name='Disciplina')),
                ('codigo_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_disciplina', to='core.Professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'professor e disciplina',
                'verbose_name_plural': 'professores e disciplinas',
                'db_table': 'professor_disciplina',
            },
        ),
    ]
